language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GeLYdmpwhSmXBxRueWyurcrQKZhb/wdJ5p9UKaVnHYTsX4CM1PRo5YudpJKguJRikvnup574ngbtK5UOimnOUUuM3UxXpENdEgW0Xs/TCq1cIoXr7bvR4kigxWZSyMlzcBRUQxReCuekN8HV97uGWodLzCF1uHaqbfl6KUiGhC69VrAhnUTvM+lTd0B1ny4577jo37i4NGvL4eG64bAQJioBvUK56fvqVksK4wxSV1gegHOzGRD5G1SwErvAtPefUcKs/pWqur77HLYaC0Kpul1oFfTjZuOpT6aAOxrGr37x7cQUYQi/rpymz/RUIBhPP+OaFAIVv2EzVU1Kr5ywAgM+pAWcwsN792vCrTWW+CsWhEwanvMqZp5dNUUQOMPjZscPp6SW3Q+1UKeg6Op4XbVmrdtdKJ7aZt9VloQ/RGQB4DOK34/fHkGdsXjHgvd4lYnvIhReYESDpT1FHiLV7/i4xCnPD9yg3++yBhPs6Zc4q3jA84xlcSfyYxHteT0CP3EQVNHo0hyHRbC03Gqqsy3PoZkpshXWt0V2TTk4UEWZtpuGDdvm9jh8NQ7CiDKtTmtQSAGMeKKhQR7ixnyManx8gU96rfJ/8cqqrs4KOW4g2ij2+9ZkyYB0O52jp8C+UuBRhQ3x+7KsblRzYj0JFy+uVMDHqngHuF1BuA1UfvY=
  app: web-base
  on:
    repo: pfernandom/web-base
