language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: KCF73w+JMPTrCDBDWd+l+6jhnS9xpqIpKo2htU0QtUkY4BO1BLPl3/yXncg5L+gzQa8k8upLtPP1pgaXgRO+Go3ILp3ucoeZFHJmzQk2zBcEbqhChxxYETaYum8b5x3LFBoympWqVHf++ezBWi8aDVETuh1TSpBP1VyaVgtrGgr0V/Mz2Zy/s6YKRkK1bIvuMqDB81MPuJP6ZWsfe6pCz7aGS/gMVMBhsnGETVbfjtA/RSXYK8+6b6Rev8HTj5O1u5uAgtBe+yVZEGSoKCl2c63dKWFy/bYgLWlaqP+V9V9rfjK+m7Q04QdZ63ZsT/A0F+XAq4Dn9w4zBmrVlxExZiBQO9T57XHPS2Fn6sdRoZRgiyRokIhL5rd9GzFRXghlUL60ty+A2hcVLnBPqLlWJ6SfVDvaCjoMXxwxj31tmGJLa0J2XXY7kSXyV57VjDQrrahDAS+sOTXnd8j/Z07aBi1Dr4RtrvNRv+GbKdEGVFU+fF6I3A4BP4o4F0GUR2LrLzgbCM1pCKVPZIM2vpIU/ivgvsrmoIx478OLnx3RKyEmX0hf4JwDlTvtrWIv09M3Q4pOzm5ZeYZ6/pHHfTfXAPyOYawtk1uvyhmQyEE5tSt/hsL1oFrNSsQVMAWf9eGxaCi7OShQDK4cLaFFdgu/aSZbzAiE+n4ueVTSRAQK9CQ=
  app: web-base
  on:
    repo: pfernandom/web-base
