language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BVNKX7emkKU9AsV5NVwjOngDFeyFCYbC34XSKAmB5hcmyEoEcKerR4VfLFGwk+N3bDQ2Y9XLQt0gh1Nr+8eCklAaEMRZtxS2WjAN3Nue5OjfcJs1HK7Omk1U6Db3JrSsn1mnS5ai326at8+2/5jcUkvSR/shgP8Y5EmS7EQlMEB7BreLhonsJpjLrEqx7FWcaJsoK4GzLjfrGfKUFL/dUoSNukjMzbZZQSvq0tk/3U/+IKmQ1mW4JmhMx/3UevX0SZlBm0f/KCkK4J1+8YlTP5hnaYKPYnaGAKp0f05gDWH+vxzhtde5kMnNek95qIjDI2MWa/gOrdOGJoE/4IiR15vHpGrkwAzXaH6aNmW8vkVhS/OqzYpEhbQpdcK4PT0faxgJ5SX/J69Wd4h4f7KBCM2F7zYRMfyatwyGd+pfO54KtT6jmV/dGjOGlPudvViSvcVKXz5wWYTU62HopjgMzj7AZHHYjLRcWYhEQu0Cn6vlBBALBL0bdzHt+Y6Sc4hSZaQzUP9B821k6zXeIQ0WOj8ZynIfofp1eB+B7ECIeIjItE65g8ID8C/upEF1lIFPjP9vCBX6cfY2K3hU5gOYY0B0PTwmAm6lsxIZLZQRCjuUO11dsrA3gj+ZknVPBw3YmW6YcqVxLk43Szpgw7NU3FeM/3eo2NSmRQGDkByj22s=
  app: web-base
  on:
    repo: pfernandom/web-base
