language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ZxSX0rjjHEMlqkTqwRFQkdVzhFsbjbNN20G1mGmswftCSAQHJuKBgqXMWEEyLjbjZpu7dq3XarYq69ovmfMpwtZmF9dXpZnhiGEt6qEbH1BSlmlvSO3Hhg+wAjd7OGcyuANRJwP7GpRJ1yUIcLB9pnB3t+ViF2UV9F8dpxJTCY8ENBP5neKS38HRlmbk6iTEwXnTJRdMHxPxIsy3Ya5suY7AzhIbDpWSjA2ePoO6BkZ/8U2Vby63WbVzYSkAYwWRgYtwsBfVY9/co2Fuo1LadKKnVweW+hQRNQ6z1ScVcBaBxTd8xV0efaXLoPIROqhZ3ejGU9XVdQYEgeD4V+QMO7ZQkjf5GQr2PNxlCJbGoZ4kzRlOcBRBd0b3cQxTGX998CxH4cpC5/IDSDwneaHXkAFd7x1x04HPeBFR4KBL3XAQhIe/CdcreZKCM51MCa7sqp1XZrcEQkCan9Mh5472O1rCV/z9qCsJRX38mCBrhLIr4EN0+HUV745c6ybv/D/TG73s0kDWifx4PmW3zdZPBCEpBZzwI4mw8O29kuS6Oo1ChjAC8e/P1uo/Vpw4dpxNtby1xFRCDEvqmDdAF1nzikBVzUa5hIuxRgtwTIz3N3vqNTwIyoSgwV1F7fBb7f+r4Iv9UYjK1VMloLuMjjl6aCsNkcuSeXswUlTMQc3tEtI=
  app: web-base
  on:
    repo: pfernandom/web-base
