language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: RMI/T5MW2PASPbAlcyjLHwv2dzZdszlx5A7G8fJENiV51kdtBb05HC3OGJQuWe0W5LdDEvJ45bmWWd25lIjl4+lxYgRPEXqZyTPPHTRSE6ZEGe+Xjp1UoTNi3VcyHzlMzVr7ztnRClcBRXUK/X8DaHmw59A2gkfhKSK/YGl0ZdeB1ga7IOwta72MOV5w1zOdRo3732RABV0H0/m/6FgiKO2GgJ7Yxo6/VTNHXogmIFv9yx50TjwZCsO6GzW4xTncxLb5eFZgdntZqx5SLN1tkqJjKjfWPQPelwiInkIVWpDZHS2ytf3lAbNexi3kMyx2KVch3o/ugaCI+VqHfzkLbmmpiof7XRZwuxG7if7lJ0UoHDuFnsMd4DRzVC4KaX1FqVtc1ZsJgkLwMYAiBau9PBIrTMTkGjsRyBg8r7eM3vgn8dbgg60aEKW5eGgewTDgmjp4BqjmrcT8LCA/8vzQsH5WsUJX/PJ5Cqq2tXXM2Dep/HFGQWC2R0o77Hk2UUsGWD0aBkGj+zk+JIOS8q6oCAtM39x0ehbxEl3BCtFVyuX84jeCqq/KGwBl6fG37BABCW9q3tVQnQIlwGidO0W3WSJ+MYz23Dfw1qyG4Lvv9+PQiCvtMvKnpcXc4po42oXygnVrrmUnZNTb+7ghmQ6M7dvMaZDp0RQ75ZugOa4klr0=
  app: web-base
  on:
    repo: pfernandom/web-base
