language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ipiqQy+dqsUXRZi0poomOOGL6SsT478QztFal8ghk3w4jslxCRd2OPtJe+wEpVfslRJb7lPxbAVupIkBZ6NKNpP/L35NQd+WNfGj1izjex90cLfS/vbkPa5uVcqOyg4WxwV1wAcSXigbu+fI627cl0F5UsMMzAM8cxT+hfRsvtVtUsG+703HGq2Pcw08KsbsnWOwt2WnXTClH2StediMBmgr3rCu+dcoz0z3zKF5mmpeBPeC7JHiyPQnqGC/7dMD3CQEG8Ytjnth9MlH3fgOXFibYBFombCPv9wR0bB/xrJ7Ie9MtUJqeNPyQemv2ANO5V8bUOhJcstGVaMn1hTnzP7wCVZYW21g5Ptd/VDzztWI+KMm196Gc9NW1XQ/MG7fuuJOp7jzlc2wfYEkYAUZ9cwQWJBeK2xNHYvFCmpd6ooihds8FfrPHh6bY8rONXFJ210VP/dIZI3ykNqmLc8TeuLjORGoS6JhmgOs0lb73qHO78vuQov/iq2MolO+RdkYW5NzteDt7KHxFTbfKw7syqIRkRfZkIwZcMwmbF6h1PbOvXEWb3XCrMAxIDKO+9fNUz6UEXgOP0j5etDLZPEtl1Lz8k6Y0OXneVlMR/Dqi/HURcO0eKxP7kmsR2TRgvnZa07YPL3fln921O+4w6xQYfWHfQEi2uJXAAfmQeRZpXY=
  app: web-base
  on:
    repo: pfernandom/web-base
