language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: HC5YY/SEKQg8g8vXvQchVczw30LTuql+hS65uyWP7gy7nQ+2LzjEXKxOq32l6GTHZePK8bz4pUxfNCHKW2RetkVyf6eYqv5uvVEWtJLwdRGOPYm7uFdsTLOnG2UD3kbmIOed9RaQFJ0FAf4za4vGFomqbIH4an1ZE3GzFP5RJvAhH/UzMYz3+4cvP6+kh6oZv3rmR0ts5K/q/zfE5EK2lauWM/93wlAkdLp+G7332CKVcnTAJ02IUI3Dn0ZlNxsXfVuMZUrVK6Uc4Gqk6rGOehDfgur8wFwZFltwxuDag+xCMWXY5EmZtcqSVVxstyGWoENfCf2/FCJFfF1wSxATa7SjPXwmnQCgB0aeuVanLEOEGn/UGxa/SgYriGWtvNcheVsrEZ65mOQOhapz6Myk8fKl8qyEF0PhD5QsCkYzndE5015E2rXOgjIFqyO2n9HSUIXcauD91UbFKajMMq1JRy1KW6IeZxG/YeyFhTpy6KzZ5yEZ8nf6Rh8BWs5bfqKCYCglKaWChn1FOtjaKBvnWBHLmJXjz9vblT29WGzwvTx0i33IxG7I3EPFVctPFbHaeVBJlU6oiW7hJchpWUOTT+WdSBiQ6qyCnZrVKtczQBfQB/LpxodYXS4hvXKwEnE/ZddDDSmQWAHKgNKxFkz4BvOW+qNcAae/5QBkd512Fgg=
  app: web-base
  on:
    repo: pfernandom/web-base
