INSERT INTO users(userid, username,email,password,enabled) VALUES (1,'admin','abc@abc.com','$2a$08$gnERKdidfhKIxTEs16aiTOJI9CUWLLtAJBSN/wVFVR.Lsr4unS7UK', true);
INSERT INTO users(userid, username,email,password,enabled) VALUES (2,'user','abc@abc.com','$2a$08$YsPgl7JXD83Q2iyIVm8G4e0AZyWMgsxFzXAihWpQdMx9bBnz6J4ie', true);
INSERT INTO user_roles(user_role_id, userid, role) VALUES (1,1,'ROLE_USER');
INSERT INTO user_roles(user_role_id, userid, role) VALUES (2,1,'ROLE_ADMIN');
INSERT INTO user_roles(user_role_id, userid, role) VALUES (3,2,'ROLE_USER');

INSERT INTO state(id, name) VALUES (1,'Aguascalientes');
INSERT INTO state(id, name) VALUES (2,'Baja California');
INSERT INTO state(id, name) VALUES (3,'Baja California Sur');
INSERT INTO state(id, name) VALUES (4,'Campeche');
INSERT INTO state(id, name) VALUES (5,'Coahuila');
INSERT INTO state(id, name) VALUES (6,'Colima');
INSERT INTO state(id, name) VALUES (7,'Chiapas');
INSERT INTO state(id, name) VALUES (8,'Chihuahua');
INSERT INTO state(id, name) VALUES (9,'Distrito Federal');
INSERT INTO state(id, name) VALUES (10,'Durango');
INSERT INTO state(id, name) VALUES (11,'Guanajuato');
INSERT INTO state(id, name) VALUES (12,'Guerrero');
INSERT INTO state(id, name) VALUES (13,'Hidalgo');
INSERT INTO state(id, name) VALUES (14,'Jalisco');
INSERT INTO state(id, name) VALUES (15,'México');
INSERT INTO state(id, name) VALUES (16,'Michoacán');
INSERT INTO state(id, name) VALUES (17,'Morelos');
INSERT INTO state(id, name) VALUES (18,'Nayarit');
INSERT INTO state(id, name) VALUES (19,'Nuevo León');
INSERT INTO state(id, name) VALUES (20,'Oaxaca');
INSERT INTO state(id, name) VALUES (21,'Puebla');
INSERT INTO state(id, name) VALUES (22,'Querétaro');
INSERT INTO state(id, name) VALUES (23,'Quintana Roo');
INSERT INTO state(id, name) VALUES (24,'San Luis Potosí');
INSERT INTO state(id, name) VALUES (25,'Sinaloa');
INSERT INTO state(id, name) VALUES (26,'Sonora');
INSERT INTO state(id, name) VALUES (27,'Tabasco');
INSERT INTO state(id, name) VALUES (28,'Tamaulipas');
INSERT INTO state(id, name) VALUES (29,'Tlaxcala');
INSERT INTO state(id, name) VALUES (30,'Veracruz');
INSERT INTO state(id, name) VALUES (31,'Yucatán');
INSERT INTO state(id, name) VALUES (32,'Zacatecas');
